### ISSUE TITLE
Output of score values

### ISSUE THREAD

**Issue by mlhoggard** [KennthShang/HostG#3]
Hi there,

Thanks for your reply to my question in #2 

I just had a quick couple of unrelated follow up questions: 

- Is there currently an output file that includes the score for each match (i.e. the threshold referenced by the `-t` parameter) to enable filtering *after* the completion of the run? I may have just overlooked it in the output files, but hadn't come across this info yet. 
  - This would be useful for if e.g. `-t 0` was set for the run, but then user wished to filter by a threshold (e.g. 0.8) downstream? 
  - And/or, I'm guessing different scores might alter whether you are confident in taking the host match at a higher taxonomic rank (e.g. phylum) even if the prediction doesn't seem confident at a lower one (e.g. genus). And so, presumably the user could set their own thresholds for which taxonomic rank to take for the host prediction based on the output score? (Perhaps 0.7 might be appropriate to take the phylum level prediction, but with 0.9 you might be confident with the genus prediction?)
- I also just spotted that in `config.py` the default for `--dataset` is `'Caudoviridae'`. Does this imply that the model is specifically designed to only really cover Caudoviridae virus-host pairings, or is that line in the script there unrelated to how the actual model was trained? 

Thanks again!
Mike.

**Comment by KennthShang** [comment]
Many thanks for your suggestions! Recently I am a little bit busy. But I will fix them asap.

For the second question. The latest database is extended to all prokaryotic viruses. Also, you can extend to other interactions. 'Caudoviridae' is the name of the previous dataset.

**Comment by KennthShang** [comment]
Sorry for the late update. I got a problem with my HPC account today. The scoring problem should be fixed. But I will re-run it for double-check.

**Comment by mlhoggard** [comment]
Hi again,

Thanks for the swift updates, they're much appreciated! 

I just had a test run of the latest version with the scores output for each taxonomic rank and all seems to be working smoothly thanks.

Kind regards,
Mike.
